import { StyleSheet } from "react-native";
import {
  APP_BACKGROUND_V2,
  CARD_BORDER,
  DANGER_ICON,
  DANGER_TINT_BACKGROUND,
  ERROR_COLOR,
  ERROR_TEXT,
  FIELD_DISABLED_BACKGROUND,
  FOOTER_BORDER,
  HEADER_BUTTON_ACTIVE_BACKGROUND,
  HEADER_BUTTON_BACKGROUND,
  HEADER_TEXT,
  INDIGO_TEXT,
  INDIGO_TINT_BACKGROUND,
  ON_PRIMARY,
  PRIMARY_COLOR,
  PRIMARY_TINT_50,
  SUCCESS_COLOR,
  SUCCESS_TINT_BACKGROUND,
  TEXT_MUTED,
  TEXT_PLACEHOLDER,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  WARNING_COLOR,
} from "@/constants/colors";
import {
  MAX_CONTENT_WIDTH,
  RADIUS_LG,
  RADIUS_MD,
  RADIUS_PILL,
  RADIUS_SM,
} from "@/constants/responsive";
import {
  ALERT_BANNER,
  CARD_FORM,
  DIALOG_BOX,
  DIALOG_OVERLAY,
  FIELD_DISABLED,
  FIELD_SURFACE,
  FOOTER_BAR,
  FOOTER_BTN_CANCEL,
  FOOTER_BTN_SAVE,
  MODAL_TOPBAR,
  SEGMENT_ACTIVE,
  TAB_BTN_SURFACE,
} from "@/styles/surfaces";

/**
 * Estilos compartidos por UserFormModal y sus tabs. La capa visual sale de
 * las superficies de styles/surfaces.ts (card/input/select/footer/confirm),
 * igual que HolidaysFormModal.tsx; acá solo viven layout, tipografía y los
 * estados. El tab bar conserva el layout de adminpunchinout.tsx
 * (tabs/tabBtn) y comparte con él la superficie: TAB_BTN_SURFACE en reposo,
 * SEGMENT_ACTIVE en el activo.
 */
export function createUserFormStyles(
  scale: (size: number) => number,
  verticalScale: (size: number) => number,
  font: (size: number) => number,
) {
  return StyleSheet.create({
    flex: { flex: 1 },
    screen: { flex: 1, backgroundColor: APP_BACKGROUND_V2 },
    topBar: {
      ...MODAL_TOPBAR,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scale(8),
      paddingHorizontal: scale(16),
      paddingTop: verticalScale(48),
      paddingBottom: verticalScale(14),
    },
    iconBtn: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: RADIUS_MD,
      backgroundColor: HEADER_BUTTON_BACKGROUND,
    },
    iconBtnActive: { backgroundColor: HEADER_BUTTON_ACTIVE_BACKGROUND },
    topBarSpacer: { width: 40 },
    topBarTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: font(16),
      fontWeight: "700",
      color: HEADER_TEXT,
    },
    // ── Tab bar: layout de adminpunchinout.tsx (tabs/tabBtn/tabText) ──
    tabs: {
      flexDirection: "row",
      gap: scale(6),
      paddingHorizontal: scale(16),
      paddingTop: verticalScale(12),
    },
    tabBtn: {
      ...TAB_BTN_SURFACE,
      flex: 1,
      alignItems: "center",
      gap: scale(4),
      paddingVertical: verticalScale(10),
      paddingHorizontal: scale(2),
    },
    tabBtnActive: { ...SEGMENT_ACTIVE },
    tabText: { fontSize: font(11), fontWeight: "600", color: PRIMARY_COLOR },
    tabTextActive: { color: ON_PRIMARY },
    tabErrorDot: {
      position: "absolute",
      top: verticalScale(6),
      right: scale(8),
      width: scale(8),
      height: scale(8),
      borderRadius: RADIUS_PILL,
      backgroundColor: ERROR_COLOR,
    },
    content: {
      padding: scale(16),
      gap: verticalScale(14),
      paddingBottom: verticalScale(24),
    },
    contentTablet: {
      maxWidth: MAX_CONTENT_WIDTH,
      alignSelf: "center",
      width: "100%",
    },
    card: {
      ...CARD_FORM,
      paddingHorizontal: scale(16),
      paddingTop: verticalScale(14),
      paddingBottom: verticalScale(16),
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scale(8),
      marginBottom: verticalScale(12),
    },
    cardTitleRow: { flexDirection: "row", alignItems: "center", gap: scale(10), flexShrink: 1 },
    cardTitle: { fontSize: font(14), fontWeight: "700", color: TEXT_PRIMARY },
    label: { fontSize: font(12), fontWeight: "600", color: TEXT_SECONDARY, marginBottom: verticalScale(6) },
    labelSpaced: { marginTop: verticalScale(12) },
    required: { color: ERROR_COLOR, fontWeight: "700" },
    input: {
      ...FIELD_SURFACE,
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(10),
      fontSize: font(14),
      color: TEXT_PRIMARY,
    },
    // También pisa el fondo de select y de los campos locales de las tabs
    // (buscador de dirección, timeBox): va DESPUÉS de la base en el array.
    inputDisabled: { ...FIELD_DISABLED, color: TEXT_MUTED },
    inputInvalid: { borderColor: ERROR_COLOR },
    fieldError: { fontSize: font(12), color: ERROR_COLOR, marginTop: verticalScale(4) },
    select: {
      ...FIELD_SURFACE,
      flexDirection: "row",
      alignItems: "center",
      gap: scale(8),
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(11),
    },
    selectValue: { flex: 1, fontSize: font(14), color: TEXT_PRIMARY },
    selectPlaceholder: { flex: 1, fontSize: font(14), color: TEXT_PLACEHOLDER },
    row: { flexDirection: "row", gap: scale(10) },
    rowItem: { flex: 1 },
    inlineRow: { flexDirection: "row", alignItems: "center", gap: scale(8) },
    smallBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: scale(4),
      borderRadius: RADIUS_MD,
      backgroundColor: PRIMARY_TINT_50,
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(10),
    },
    smallBtnDisabled: { opacity: 0.5 },
    smallBtnText: { fontSize: font(13), fontWeight: "700", color: PRIMARY_COLOR },
    smallBtnDangerText: { color: DANGER_ICON },
    switchRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scale(8),
    },
    switchRowSpaced: { marginTop: verticalScale(10) },
    switchLabel: { flex: 1, fontSize: font(13), fontWeight: "600", color: TEXT_PRIMARY },
    switchValue: { fontSize: font(12), fontWeight: "700", color: TEXT_MUTED, minWidth: scale(20) },
    switchValueOn: { color: SUCCESS_COLOR },
    // ── Foto ──
    photoRow: { flexDirection: "row", alignItems: "center", gap: scale(14) },
    photoBox: {
      width: scale(96),
      height: scale(96),
      borderRadius: RADIUS_LG,
      backgroundColor: FIELD_DISABLED_BACKGROUND,
      borderWidth: 1,
      borderColor: CARD_BORDER,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    photoBoxInvalid: { borderColor: ERROR_COLOR, borderWidth: 1.5 },
    photoImage: { width: "100%", height: "100%" },
    photoActions: { flex: 1, gap: verticalScale(8) },
    photoRequired: { fontSize: font(12), fontWeight: "700", color: ERROR_COLOR },
    // ── Ult. Registros ──
    recordSection: { gap: verticalScale(6) },
    recordSectionSpaced: {
      marginTop: verticalScale(12),
      paddingTop: verticalScale(12),
      borderTopWidth: 1,
      borderTopColor: FOOTER_BORDER,
    },
    recordTitle: { fontSize: font(13), fontWeight: "700", color: TEXT_PRIMARY },
    recordEmpty: { fontWeight: "400", fontStyle: "italic", color: TEXT_PLACEHOLDER },
    recordOvertime: { color: ERROR_COLOR },
    recordRow: { flexDirection: "row", alignItems: "center", gap: scale(8) },
    recordLabel: { fontSize: font(12), color: TEXT_MUTED, minWidth: scale(72) },
    pill: {
      borderRadius: RADIUS_SM,
      paddingHorizontal: scale(8),
      paddingVertical: verticalScale(2),
      backgroundColor: FOOTER_BORDER,
    },
    pillText: { fontSize: font(11), fontWeight: "700", color: TEXT_SECONDARY },
    pillYes: { backgroundColor: SUCCESS_TINT_BACKGROUND },
    pillYesText: { color: SUCCESS_COLOR },
    pillNo: { backgroundColor: DANGER_TINT_BACKGROUND },
    pillNoText: { color: ERROR_TEXT },
    // ── Categorías ──
    categoryBlock: { marginTop: verticalScale(12) },
    categoryLabel: { fontSize: font(12), fontWeight: "600", color: TEXT_SECONDARY },
    categoryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: verticalScale(6),
    },
    checkboxRow: { flexDirection: "row", alignItems: "center", gap: scale(4) },
    checkboxText: { fontSize: font(12), fontWeight: "600", color: TEXT_SECONDARY },
    chipsWrap: { flex: 1, flexDirection: "row", flexWrap: "wrap", gap: scale(4) },
    chip: {
      borderRadius: RADIUS_PILL,
      backgroundColor: INDIGO_TINT_BACKGROUND,
      paddingHorizontal: scale(8),
      paddingVertical: verticalScale(2),
    },
    chipText: { fontSize: font(12), fontWeight: "600", color: INDIGO_TEXT },
    addTagBtn: {
      width: scale(42),
      alignSelf: "stretch",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: RADIUS_MD,
      backgroundColor: PRIMARY_TINT_50,
    },
    notice: { fontSize: font(12), color: WARNING_COLOR, marginBottom: verticalScale(4) },
    stateBox: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: verticalScale(8),
      paddingVertical: verticalScale(36),
    },
    stateText: { fontSize: font(13), color: TEXT_MUTED, textAlign: "center" },
    retryText: { fontSize: font(13), fontWeight: "700", color: PRIMARY_COLOR },
    // ── Footer / confirmación: mismas superficies que HolidaysFormModal.tsx ──
    footer: {
      ...FOOTER_BAR,
      flexDirection: "row",
      gap: scale(10),
      paddingHorizontal: scale(16),
      paddingTop: verticalScale(12),
      paddingBottom: verticalScale(28),
    },
    footerBtn: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: verticalScale(13),
      borderRadius: RADIUS_LG,
    },
    cancelBtn: { ...FOOTER_BTN_CANCEL },
    cancelText: { fontSize: font(14), fontWeight: "700", color: TEXT_SECONDARY },
    saveBtn: { ...FOOTER_BTN_SAVE },
    // Sin sombra mientras está translúcido: en Android la elevation se ve a
    // través del botón.
    saveBtnBusy: { opacity: 0.7, shadowColor: "transparent", elevation: 0 },
    saveText: { fontSize: font(14), fontWeight: "700", color: ON_PRIMARY },
    errorBanner: {
      ...ALERT_BANNER,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: scale(8),
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(10),
    },
    errorBannerText: { flex: 1, fontSize: font(13), color: ERROR_TEXT },
    confirmOverlay: {
      ...DIALOG_OVERLAY,
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    confirmBox: {
      ...DIALOG_BOX,
      padding: scale(24),
      width: "80%",
      maxWidth: 400,
    },
    confirmTitle: {
      fontSize: font(15),
      fontWeight: "700",
      color: ERROR_COLOR,
      marginBottom: verticalScale(8),
    },
    confirmMessage: { fontSize: font(14), color: TEXT_SECONDARY },
    confirmButtons: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: scale(20),
      marginTop: verticalScale(24),
    },
    confirmCancel: { color: TEXT_MUTED, fontWeight: "600", fontSize: font(14) },
    confirmConfirm: { color: ERROR_COLOR, fontWeight: "600", fontSize: font(14) },
  });
}

export type UserFormStyles = ReturnType<typeof createUserFormStyles>;
