import { StyleSheet } from "react-native";
import { APP_BACKGROUND } from "@/constants/colors";
import {
  MAX_CONTENT_WIDTH,
  RADIUS_2XL,
  RADIUS_LG,
  RADIUS_MD,
  RADIUS_PILL,
  RADIUS_SM,
} from "@/constants/responsive";

/**
 * Estilos compartidos por UserFormModal y sus tabs. Mismos valores que
 * HolidaysFormModal.tsx (card/label/input/select/footer/confirm) y el tab bar
 * de adminpunchinout.tsx (tabs/tabBtn/tabBtnActive), para que el modal se vea
 * igual al resto de formularios de la app.
 */
export function createUserFormStyles(
  scale: (size: number) => number,
  verticalScale: (size: number) => number,
  font: (size: number) => number,
) {
  return StyleSheet.create({
    flex: { flex: 1 },
    screen: { flex: 1, backgroundColor: APP_BACKGROUND },
    topBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scale(8),
      backgroundColor: "#fff",
      paddingHorizontal: scale(16),
      paddingTop: verticalScale(48),
      paddingBottom: verticalScale(14),
      borderBottomWidth: 1,
      borderBottomColor: "#F3F4F6",
    },
    iconBtn: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: RADIUS_MD,
    },
    iconBtnActive: { backgroundColor: "#EFF6FF" },
    topBarSpacer: { width: 40 },
    topBarTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: font(16),
      fontWeight: "700",
      color: "#142157",
    },
    // ── Tab bar: copia de adminpunchinout.tsx (tabs/tabBtn/tabText) ──
    tabs: {
      flexDirection: "row",
      gap: scale(6),
      paddingHorizontal: scale(16),
      paddingTop: verticalScale(12),
    },
    tabBtn: {
      flex: 1,
      alignItems: "center",
      gap: scale(4),
      backgroundColor: "#EFF6FF",
      borderRadius: RADIUS_LG,
      paddingVertical: verticalScale(10),
      paddingHorizontal: scale(2),
    },
    tabBtnActive: { backgroundColor: "#2563EB" },
    tabText: { fontSize: font(11), fontWeight: "600", color: "#2563EB" },
    tabTextActive: { color: "#fff" },
    tabErrorDot: {
      position: "absolute",
      top: verticalScale(6),
      right: scale(8),
      width: scale(8),
      height: scale(8),
      borderRadius: RADIUS_PILL,
      backgroundColor: "#DC2626",
    },
    content: {
      padding: scale(16),
      gap: verticalScale(14),
      paddingBottom: verticalScale(24),
    },
    contentTablet: {
      maxWidth: MAX_CONTENT_WIDTH,
      alignSelf: "center",
      width: "100%",
    },
    card: {
      backgroundColor: "#fff",
      borderRadius: RADIUS_2XL,
      borderWidth: 1.5,
      borderColor: "#E5E7EB",
      paddingHorizontal: scale(16),
      paddingTop: verticalScale(14),
      paddingBottom: verticalScale(16),
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scale(8),
      marginBottom: verticalScale(12),
    },
    cardTitleRow: { flexDirection: "row", alignItems: "center", gap: scale(6), flexShrink: 1 },
    cardTitle: { fontSize: font(14), fontWeight: "700", color: "#111827" },
    label: { fontSize: font(12), fontWeight: "600", color: "#374151", marginBottom: verticalScale(6) },
    labelSpaced: { marginTop: verticalScale(12) },
    required: { color: "#DC2626", fontWeight: "700" },
    input: {
      borderWidth: 1,
      borderColor: "#D1D5DB",
      borderRadius: RADIUS_MD,
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(10),
      fontSize: font(14),
      color: "#111827",
      backgroundColor: "#fff",
    },
    inputDisabled: { backgroundColor: "#F3F4F6", color: "#6B7280" },
    inputInvalid: { borderColor: "#DC2626" },
    fieldError: { fontSize: font(12), color: "#DC2626", marginTop: verticalScale(4) },
    select: {
      flexDirection: "row",
      alignItems: "center",
      gap: scale(8),
      borderWidth: 1,
      borderColor: "#D1D5DB",
      borderRadius: RADIUS_MD,
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(11),
      backgroundColor: "#fff",
    },
    selectValue: { flex: 1, fontSize: font(14), color: "#111827" },
    selectPlaceholder: { flex: 1, fontSize: font(14), color: "#9CA3AF" },
    row: { flexDirection: "row", gap: scale(10) },
    rowItem: { flex: 1 },
    inlineRow: { flexDirection: "row", alignItems: "center", gap: scale(8) },
    smallBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: scale(4),
      borderRadius: RADIUS_MD,
      backgroundColor: "#EFF6FF",
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(10),
    },
    smallBtnDisabled: { opacity: 0.5 },
    smallBtnText: { fontSize: font(13), fontWeight: "700", color: "#2563EB" },
    smallBtnDangerText: { color: "#B43333" },
    switchRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: scale(8),
    },
    switchRowSpaced: { marginTop: verticalScale(10) },
    switchLabel: { flex: 1, fontSize: font(13), fontWeight: "600", color: "#111827" },
    switchValue: { fontSize: font(12), fontWeight: "700", color: "#6B7280", minWidth: scale(20) },
    switchValueOn: { color: "#15803D" },
    // ── Foto ──
    photoRow: { flexDirection: "row", alignItems: "center", gap: scale(14) },
    photoBox: {
      width: scale(96),
      height: scale(96),
      borderRadius: RADIUS_LG,
      backgroundColor: "#F3F4F6",
      borderWidth: 1,
      borderColor: "#E5E7EB",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    photoBoxInvalid: { borderColor: "#DC2626", borderWidth: 1.5 },
    photoImage: { width: "100%", height: "100%" },
    photoActions: { flex: 1, gap: verticalScale(8) },
    photoRequired: { fontSize: font(12), fontWeight: "700", color: "#DC2626" },
    // ── Ult. Registros ──
    recordSection: { gap: verticalScale(6) },
    recordSectionSpaced: {
      marginTop: verticalScale(12),
      paddingTop: verticalScale(12),
      borderTopWidth: 1,
      borderTopColor: "#F3F4F6",
    },
    recordTitle: { fontSize: font(13), fontWeight: "700", color: "#111827" },
    recordEmpty: { fontWeight: "400", fontStyle: "italic", color: "#9CA3AF" },
    recordOvertime: { color: "#E74C3C" },
    recordRow: { flexDirection: "row", alignItems: "center", gap: scale(8) },
    recordLabel: { fontSize: font(12), color: "#6B7280", minWidth: scale(72) },
    pill: {
      borderRadius: RADIUS_SM,
      paddingHorizontal: scale(8),
      paddingVertical: verticalScale(2),
      backgroundColor: "#F3F4F6",
    },
    pillText: { fontSize: font(11), fontWeight: "700", color: "#374151" },
    pillYes: { backgroundColor: "#DCFCE7" },
    pillYesText: { color: "#15803D" },
    pillNo: { backgroundColor: "#FEE2E2" },
    pillNoText: { color: "#B91C1C" },
    // ── Categorías ──
    categoryBlock: { marginTop: verticalScale(12) },
    categoryLabel: { fontSize: font(12), fontWeight: "600", color: "#374151" },
    categoryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: verticalScale(6),
    },
    checkboxRow: { flexDirection: "row", alignItems: "center", gap: scale(4) },
    checkboxText: { fontSize: font(12), fontWeight: "600", color: "#374151" },
    chipsWrap: { flex: 1, flexDirection: "row", flexWrap: "wrap", gap: scale(4) },
    chip: {
      borderRadius: RADIUS_PILL,
      backgroundColor: "#E0E7FF",
      paddingHorizontal: scale(8),
      paddingVertical: verticalScale(2),
    },
    chipText: { fontSize: font(12), fontWeight: "600", color: "#3730A3" },
    addTagBtn: {
      width: scale(42),
      alignSelf: "stretch",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: RADIUS_MD,
      backgroundColor: "#EFF6FF",
    },
    notice: { fontSize: font(12), color: "#B45309", marginBottom: verticalScale(4) },
    stateBox: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: verticalScale(8),
      paddingVertical: verticalScale(36),
    },
    stateText: { fontSize: font(13), color: "#6B7280", textAlign: "center" },
    retryText: { fontSize: font(13), fontWeight: "700", color: "#2563EB" },
    // ── Footer / confirmación: copia de HolidaysFormModal.tsx ──
    footer: {
      flexDirection: "row",
      gap: scale(10),
      paddingHorizontal: scale(16),
      paddingTop: verticalScale(12),
      paddingBottom: verticalScale(28),
      backgroundColor: "#fff",
      borderTopWidth: 1,
      borderTopColor: "#F3F4F6",
    },
    footerBtn: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: verticalScale(13),
      borderRadius: RADIUS_LG,
    },
    cancelBtn: { backgroundColor: "#F3F4F6" },
    cancelText: { fontSize: font(14), fontWeight: "700", color: "#374151" },
    saveBtn: { backgroundColor: "#2563EB" },
    saveBtnBusy: { opacity: 0.7 },
    saveText: { fontSize: font(14), fontWeight: "700", color: "#fff" },
    errorBanner: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: scale(8),
      backgroundColor: "#FEF2F2",
      borderWidth: 1,
      borderColor: "#FECACA",
      borderRadius: RADIUS_LG,
      paddingHorizontal: scale(12),
      paddingVertical: verticalScale(10),
    },
    errorBannerText: { flex: 1, fontSize: font(13), color: "#B91C1C" },
    confirmOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    confirmBox: {
      backgroundColor: "#fff",
      borderRadius: RADIUS_LG,
      padding: scale(24),
      width: "80%",
      maxWidth: 400,
      elevation: 5,
    },
    confirmTitle: {
      fontSize: font(15),
      fontWeight: "700",
      color: "#DC2626",
      marginBottom: verticalScale(8),
    },
    confirmMessage: { fontSize: font(14), color: "#444" },
    confirmButtons: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: scale(20),
      marginTop: verticalScale(24),
    },
    confirmCancel: { color: "#6B7280", fontWeight: "600", fontSize: font(14) },
    confirmConfirm: { color: "#DC2626", fontWeight: "600", fontSize: font(14) },
  });
}

export type UserFormStyles = ReturnType<typeof createUserFormStyles>;
